# Copyright 2023 Ant Group Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

networks:
  nn-benchmark:
    ipam:
      config:
        - subnet: 172.16.238.0/24
      driver: default
    name: nn-benchmark
services:
  node_0:
    command: |
      python3 -m pip install -U pip
      python3 -m pip install spu
      python3 -m spu.examples.python.utils.nodectl -c /home/admin/dev/.circleci/benchmark.json start --node_id node:0
    image: secretflow/spu-ci:latest
    networks:
      nn-benchmark:
        ipv4_address: 172.16.238.2
    volumes:
      - ${PWD}:/home/admin/dev/
  node_1:
    command: |
      python3 -m pip install -U pip
      python3 -m pip install spu
      python3 -m spu.examples.python.utils.nodectl -c /home/admin/dev/.circleci/benchmark.json start --node_id node:1
    image: secretflow/spu-ci:latest
    networks:
      nn-benchmark:
        ipv4_address: 172.16.238.3
    volumes:
      - ${PWD}:/home/admin/dev/
  node_2:
    command: |
      python3 -m pip install -U pip
      python3 -m pip install spu
      python3 -m spu.examples.python.utils.nodectl -c /home/admin/dev/.circleci/benchmark.json start --node_id node:2
    image: secretflow/spu-ci:latest
    networks:
      nn-benchmark:
        ipv4_address: 172.16.238.4
    volumes:
      - ${PWD}:/home/admin/dev/
  node_3:
    command: |
      python3 -m pip install -U pip
      python3 -m pip install spu
      python3 -m spu.examples.python.utils.nodectl -c /home/admin/dev/.circleci/benchmark.json start --node_id node:3
    image: secretflow/spu-ci:latest
    networks:
      nn-benchmark:
        ipv4_address: 172.16.238.5
    volumes:
      - ${PWD}:/home/admin/dev/
  node_4:
    command: |
      python3 -m pip install -U pip
      python3 -m pip install spu
      python3 -m spu.examples.python.utils.nodectl -c /home/admin/dev/.circleci/benchmark.json start --node_id node:4
    image: secretflow/spu-ci:latest
    networks:
      nn-benchmark:
        ipv4_address: 172.16.238.6
    volumes:
      - ${PWD}:/home/admin/dev/
