on:
  release:
    types: [created]
  workflow_dispatch
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: secretflow-spu-deploy
        id: secretflow-spu-deploy
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
